# ==========================================
# Infamy SMP - Main Configuration
# ==========================================

prefixes:
  infamy_21: "&4[Most Infamous]"
  infamy_16: "&c[Extremely Dangerous]"
  infamy_11: "&6[Dangerous]"
  infamy_6: "&e[Risky]"
  infamy_1: "&a[Normal]"
  neutral: "&a[Normal]"
  honor: "&b[Honorable]"

# Global Toggle Settings
settings:
  drop-bottle-on-kill: true # Allow player kills to either instant consume or drop on floor
  allow-withdraw: true # Allow players to use /infamy withdraw
  boss-bottle-announce: true # Sound effect announcements for Pure Bottle
  boss-bottle-sound: true # Sound effect for the Pure Bottle
  show-ability-particles: true # VFX for abilities
  team-easy-coord: true # Allows teammates to use /infamy team coords and see locations of their members
  show-consumption-beacon: true # Spiraling Beacon effect
  nametag-team-color: true # Shows team name and color above player heads
  team-friendly-fire: true # Disabling this stops teammates from hurting each other
  bottle-particles: # Change Particle effect type (also changes the Beacon spiral effect to match with corresponding botle)
    infamy:
      enabled: true
      particle: "END_ROD"
    honor:
      enabled: true
      particle: "GLOW"
    pure:
      enabled: true
      particle: "DUST"

custom-model-data: # Do not touch this, used for the Numbering of Textures on Infamy/Honor/Pure bottles
  infamy_bottle: 10001
  honor_bottle: 10002
  boss_bottle: 10003

# ==========================================
# Ability Balancing Configuration
# ==========================================
abilities-config:
  sword-block:
    cooldown-seconds: 60
    duration-seconds: 5
    damage-taken-multiplier: 0.5 # 50% damage block
  shield-recovery:
    cooldown-seconds: 25 # 25 seconds
    health-cost: 4.0 # 4.0 = 2 Hearts
  bleeding-edge:
    cooldown-seconds: 60 # 1 minute
    duration-ticks: 5 # 5 seconds
    damage-per-tick: 1.0 # 1.0 = Half a Heart
    iframe-ticks: 10 # 10 ticks = 0.5
  mace-slam:
    cooldown-seconds: 60 # 1 minutez
    forward-velocity: 1.5 # forward velocity when aiming dead ground forward
    upward-velocity: 1.4 # 1.4 - 12 blocks high vertical
    max-splash-damage: 12.0 # 12.0 = 6 Hearts
    fall-damage-reduction: 0.25 # 0.25 = 25% less fall damage taken
  hellcrush:
    cooldown-seconds: 900 # 15 minutes
    duration-seconds: 300 # 5 minutes
    stat-reduction-percentage: 0.5 # 0.5 = 50%, 1.0 = 100%, 0.1 = 10%

# ==========================================
# Infamy Mechanics (Positive Points)
# ==========================================
infamy_abilities:
  sword_block:
    enabled: true
    level: 3
  shield_recovery:
    enabled: true
    level: 6
  axe_pierce:
    enabled: true
    level: 9
  double_potions:
    enabled: true
    level: 12
  villager_wary:
    enabled: true
    level: 12
  passive_resistance:
    enabled: true
    level: 15
  bad_fortune:
    enabled: true
    level: 15
  bleeding_edge:
    enabled: true
    level: 18
  mace_slam:
    enabled: true
    level: 20
  boss_sacrifice:
    enabled: true
    level: 21

# ==========================================
# Honor Mechanics (Negative Points)
# ==========================================
honor_abilities:
  good_fortune:
    enabled: true
    level: 3
  hero_of_the_village:
    enabled: true
    level: 6
  halved_potions:
    enabled: true
    level: 9
  weapon_cooldowns:
    enabled: true
    level: 12

elytra-recipe:
  enabled: true
  shape:
    - "PNP"
    - "NSN"
    - "F F"
  ingredients:
    P: "PHANTOM_MEMBRANE"
    N: "NETHERITE_INGOT"
    S: "NETHER_STAR"
    F: "FEATHER"