# ==========================================
# Infamy SMP - Main Configuration
# ==========================================

prefixes:
  infamy_21: "&4[Most Infamous]"
  infamy_16: "&c[Extremely Dangerous]"
  infamy_11: "&6[Dangerous]"
  infamy_6: "&e[Risky]"
  infamy_1: "&a[Normal]"
  neutral: "&a[Normal]"
  honor: "&b[Honorable]"

# Global Toggle Settings
settings:
  drop-bottle-on-kill: true
  allow-withdraw: true
  boss-bottle-announce: true
  boss-bottle-sound: true
  show-ability-particles: true # Toggles all combat trails, lava splashes, and shockwaves
  show-consumption-beacon: true # Toggles the spiral beacon effect when drinking custom bottles
  bottle-particles:
    infamy:
      enabled: true
      particle: "END_ROD"
    honor:
      enabled: true
      particle: "GLOW"
    pure:
      enabled: true
      particle: "DUST" # DUST is the 1.21 name for Redstone particles

custom-model-data:
  infamy_bottle: 10001
  honor_bottle: 10002
  boss_bottle: 10003

# ==========================================
# Infamy Mechanics (Positive Points)
# ==========================================
infamy_abilities:
  sword_block:
    enabled: true
    level: 3
  shield_recovery:
    enabled: true
    level: 6
  axe_pierce:
    enabled: true
    level: 9
  double_potions:
    enabled: true
    level: 12
  villager_wary:
    enabled: true
    level: 12
  passive_resistance:
    enabled: true
    level: 15
  bad_fortune:
    enabled: true
    level: 15
  bleeding_edge:
    enabled: true
    level: 18
  mace_slam:
    enabled: true
    level: 20
  boss_sacrifice:
    enabled: true
    level: 21

# ==========================================
# Honor Mechanics (Negative Points)
# ==========================================
honor_abilities:
  good_fortune:
    enabled: true
    level: 3
  hero_of_the_village:
    enabled: true
    level: 6
  halved_potions:
    enabled: true
    level: 9
  weapon_cooldowns:
    enabled: true
    level: 12

elytra-recipe:
  enabled: true
  shape:
    - "PNP"
    - "NSN"
    - "F F"
  ingredients:
    P: "PHANTOM_MEMBRANE"
    N: "NETHERITE_INGOT"
    S: "NETHER_STAR"
    F: "FEATHER"