name: InfamySMP
description: ${description}
version: '${version}'

main: com.enxivity.infamy.InfamySMP
api-version: '1.21.11'
load: POSTWORLD

authors: [ NelA470 ]

commands:
  infamy:
    description: Master command for the Infamy SMP system.
    aliases: [inf]
    usage: /infamy <subcommand>
  team:
    description: Manage your team.
    aliases: [teams, t]
    usage: /team <create|invite|accept|decline|leave|kick|list|color|coords|chat>

permissions:
  infamysmp.admin:
    description: Allows the use of Infamy admin commands.
    default: op