name: InfamySMP
description: $description
version: '${version}'

main: com.enxivity.infamy.InfamySMP
api-version: '1.21.11'
load: POSTWORLD

authors: [ NelA470 ]

commands:
  infamy:
    description: Master command for the Infamy SMP system.
    usage: /infamy <team|add|points> ...
    aliases: [inf]